PostSys/Controllers/ClassesController.cs
using PostSys.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.Entity;
using PostSys.ViewModels;
using Microsoft.AspNet.Identity;

namespace PostSys.Controllers
{
	public class ClassesController : Controller
	{
		private ApplicationDbContext _context;

		public ClassesController()
		{
			_context = new ApplicationDbContext();
		}


		// GET: Classes
		/*[Authorize(Roles = "Marketing Manager")]*/
		public ActionResult Index(string searchString)
		{
			var getAllClasses = _context.Classes.Include(m => m.Coordinator).Include(m => m.Faculty);
			
			if (!String.IsNullOrEmpty(searchString))
			{
				getAllClasses = getAllClasses.Where(s => s.Name
										     .Contains(searchString) || 
											 s.Faculty.Name.Contains(searchString));
			}

			return View(getAllClasses.ToList());
		}

		// GET: Classes/Create
		/*[Authorize(Roles = "Marketing Manager")]*/
		[HttpGet]
		public ActionResult Create()
		{

			//get all account in coordinator role
			var role = (from r in _context.Roles where r.Name.Contains("Marketing Coodinator") select r)
															 .FirstOrDefault();
			var showCoordinator = _context.Users.Where(x => x.Roles.Select(y => y.RoleId)
									  .Contains(role.Id))
									  .ToList();

			var showFaculty = _context.Faculties.ToList();

			var newFacultyViewModel = new CoordinatorFacultyViewModel
			{
				Faculties = showFaculty,
				Coordinators = showCoordinator
			};
			return View(newFacultyViewModel);
		}

		/*[Authorize(Roles = "Marketing Manager")]*/
		[HttpPost]
		public ActionResult Create(Class @class)
		{
			if (!ModelState.IsValid)
			{
				return View("~/Views/ErrorValidations/Null.cshtml");
			}

			var checkCoordinatorInFaculty = _context.Classes.Any(c => c.CoordinatorId == @class.CoordinatorId ||
																   c.FacultyId == @class.FacultyId);

			if (checkCoordinatorInFaculty == true)
			{
				return View("~/Views/ErrorValidations/Exist.cshtml");
			}

			var newClass = new Class
			{
				Name = @class.Name,
				FacultyId = @class.FacultyId,
				CoordinatorId = @class.CoordinatorId
			};

			_context.Classes.Add(newClass);
			_context.SaveChanges();
			return RedirectToAction("Index");
		}

		/*[Authorize(Roles = "Marketing Manager")]*/
		[HttpGet]
		public ActionResult Delete(int Id)
		{
			var classInDb = _context.Classes.SingleOrDefault(c => c.Id == Id);

			if (classInDb == null)
			{
				return HttpNotFound();
			}

			_context.Classes.Remove(classInDb);
			_context.SaveChanges();

			return RedirectToAction("Index");
		}

		/*[Authorize(Roles = "Marketing Coodinator")]*/
		[HttpGet]
		public ActionResult Mine()
		{
			var mineId = User.Identity.GetUserId();

			var mineFaculty = _context.Classes.Where(m => m.CoordinatorId == mineId).Include(m => m.Faculty).Include(m => m.Coordinator).ToList();

			return View(mineFaculty);
		}
	}
}

PostSys/Views/Classes/Create.cshtml
@model PostSys.ViewModels.CoordinatorFacultyViewModel
@{
	ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Classes", FormMethod.Post))
{
	<div class="form-group">
		@Html.LabelFor(p => p.Class.Name)
		@Html.TextBoxFor(p => p.Class.Name, new { @class = "form-control" })
		@Html.ValidationMessageFor(p => p.Class.Name, "", new { @class = "text-danger" })
	</div>


	<div class="form-group">
		@Html.LabelFor(m => m.Class.CoordinatorId)
		@Html.DropDownListFor(m => m.Class.CoordinatorId,
			new SelectList(Model.Coordinators, "Id", "Email"), "Select Coordinator",
			new { @class = "form-control" }
		)
	</div>

	<div class="form-group">
		@Html.LabelFor(m => m.Class.FacultyId)
		@Html.DropDownListFor(m => m.Class.FacultyId,
			new SelectList(Model.Faculties, "Id", "Name"), "Select Faculty",
			new { @class = "form-control" }
		)
	</div>

	<button type="submit" class="btn btn-primary">Assign</button>
}

PostSys/Views/Classes/Index.cshtml
@model IEnumerable<PostSys.Models.Class>
@{
	ViewBag.Title = "Index";
}

<h2>Index</h2>

@using (Html.BeginForm("Index", "Classes", FormMethod.Get))
{
	<p>
		Find by Class name: @Html.TextBox("SearchString")
		<input type="submit" value="Search" />
	</p>

	<table class="table table-hover">
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Coordinator Name</th>
			<th>Faculty</th>
			<th>Delete</th>
		</tr>
		@foreach (var item in Model)
		{
			<tr>
				<td>@item.Id</td>
				<td>@item.Name</td>
				<td>@item.Coordinator.UserName</td>
				<td>@item.Faculty.Name</td>
				<td>@Html.ActionLink("Delete", "Delete", new { id = item.Id })</td>
			</tr>
		}
	</table>
}

PostSys/Views/Classes/Mine.cshtml
@model IEnumerable<PostSys.Models.Class>
@{
	ViewBag.Title = "Mine";
}

<h2>Mine</h2>

@using (Html.BeginForm("Mine", "Classes", FormMethod.Get))
{
<table class="table table-hover">
	<tr>
		<th>Coordinator Name</th>
		<th>Faculty Email</th>
	</tr>
	@foreach (var item in Model)
	{
		<tr>
			<th>@item.Coordinator.Email</th>
			<th>@item.Faculty.Name</th>
		</tr>
	}
</table>
}